### ISSUE TITLE
Can't open/toggle tree view

### ISSUE THREAD

**Issue by gchp** [olmokramer/atom-autohide-tree-view#14]
With `autohide-tree-view` disabled or uninstalled, I can use `Ctrl + \` to toggle the tree. When I enable it, `Ctrl + \` does not toggle the tree. Also, if I have the tree visible, then enable autohide-tree-view, the tree remains visable and does not hide. I can manually hide it, however then it does not open either via the keybinding, or by using the mouse.

Atom version: `0.188.0`
Linux - Ubuntu 14.04

**Comment by gchp** [comment]
Binding to other keys gives the same result too: nothing.

**Comment by olmokramer** [comment]
Thanks for reporting the bug. I'll try too look at it this weekend, but I'm in the middle of my exams period, so maybe it will be somewhere next week.

With `autohide-tree-view` <em>enabled</em>, which command is being executed according to the keybinding resolver? In case you don't know, you can open the keybinding resolver by pressing <kbd>Ctrl+.</kbd>.

Did you try reloading Atom after enabling the package? If not, does it work when you do?

I think I'm going to revisit the keybindings soon, as I'm not really happy with them in general. Maybe I'll even rewrite the entire package, there's more things than just the keybindings I don't really like right now.

**Comment by olmokramer** [comment]
I just published a new version, I did a complete rewrite of the package. It might very well fix your problems. Please let me know if it works.
Cheers

**Comment by gchp** [comment]
Still happening, unfortunately.

The resolver says this is being executed: `autohide-tree-view:toggle-visible`.

Tried reloading & restarting, no change. Any ideas?

**Comment by olmokramer** [comment]
Can you try running the `tree-view:show` command and then try again?

**Comment by gchp** [comment]
Hmm, it started working again, without me changing anything. Seems to be somewhat intermittent. I'll play around a little and see if I can break it again, and try give you some more information on what might be going on & triggering it to happen.

**Comment by olmokramer** [comment]
Hmmmm, weird. At least it's a good thing that it works now :)
Please let me know if anything breaks again.

**Comment by gchp** [comment]
Will do. I'll close this for now. Thanks!

**Comment by olmokramer** [comment]
Thank you too :)
