### ISSUE TITLE
Hover Option Does Not Allow New/Rename File/Folder

### ISSUE THREAD

**Issue by jzumbrun** [olmokramer/atom-autohide-tree-view#28]
http://screencast.com/t/M1IjtwXV

atom: 1.0.2
autohide-tree-view: 0.21.1

When the "Show On" setting is set for hover the New/Rename File/Folder action only works the first time after the setting has been made. The click setting works fine. 
Subsequent actions to create a new file folder or to rename them using the hover option never opens the add/rename popup. Actually it will open it, it just flickers and disappears.

**Comment by olmokramer** [comment]
Hi Jon,

Thanks for reporting the issue and for the screencast! I've never noticed this myself, but I'll play around and see if I can trigger it. Could you give me a list of the packages you have installed?

Cheers, Olmo

**Comment by jzumbrun** [comment]
No problem:

```
Sublime-Style-Column-Selection@1.3.0
atomic-game-engine@0.4.5
autocomplete-paths@1.0.2
autocomplete-php@0.3.6
autohide-tree-view@0.21.1
highlight-line@0.11.0
language-javascript-jsx@0.3.7
linter@1.2.3
linter-php@0.0.15
project-manager@1.15.11
symbols-tree-view@0.9.3
twilight-syntax@0.7.0
```

**Comment by olmokramer** [comment]
Hey, I tried to reproduce this, but I just can't... :( Anyway, I released a new version with a lot of the code rewritten, so I was hoping maybe this got fixed in the meantime? Please let me know. If it's not fixed, could you also give me your autohide-tree-view configuration? Thanks

**Comment by bewam** [comment]
Sometimes, create/rename... doesn't trigger anything when on hover. If I change the option to click/hover and fallback to hover, works like a charm.
It's not always reproducible.  :-/

**Comment by olmokramer** [comment]
I think I know what the issue is, and have found a fix for it. It was an issue with modal panels in general (you might notice the same when opening the command palette). I'll include it in the next release.

**Comment by olmokramer** [comment]
The new version is up. Please let me know if it works :)

**Comment by jzumbrun** [comment]
Its working now thanks!

**Comment by olmokramer** [comment]
Awesome! There might be some packages where this is still happening, but it should be easy to fix it for those packages. Please submit an issue with the specific package that's bugged if you notice it again

**Comment by OmgImAlexis** [comment]
I'm using 0.23.1 with a default install of autohide-tree-view and I can't create, rename, move or do anything else that requires the omni-panel to open without pinning the tree-view. When it's in autohide mode all I get is a flash of the omnibox.

**Comment by rugk** [comment]
Also using 0.23.1 and can't rename or duplicate a file. It seems to have something to do with the box at the top where you should enter a name (for the renamed or the new file). It appears for a second and later it quickly disappears afterwards.
If I pin the panel (with the button at the right top) I can rename/duplicate files without any problems BTW.

Atom 1.0.5
Windows 7

**Comment by olmokramer** [comment]
How do you call the duplicate (etc.) commands? From the context menu, a key binding, the command palette or something else?

**Comment by rugk** [comment]
The context menu. The same like I call the rename command.

**Comment by rugk** [comment]
And new file isn't possible too, so it's exactly like @jzumbrun reported it before.

**Comment by olmokramer** [comment]
Could you please check if it works when you
1. select a folder in the tree view
2. press <kbd>a</kbd> on your keyboard

or
1. open the tree view
2. open the command palette
3. run `Tree View: Add File`

There may be some issues with right clicking the tree view. If the steps above work, that would confirm it's something to do with right click.

**Comment by OmgImAlexis** [comment]
Pressing <kbd>a</kbd> works but right clicking still flashes the omnibox and then disappears. Focus no longer gets stuck on the treeview after the flash though so that's fixed.

**Comment by olmokramer** [comment]
Ok, I'll look into it. I probably have to ignore some click events when it's a right click. Thanks.

**Comment by olmokramer** [comment]
Do you have click events enabled in the `showOn` setting?

**Comment by OmgImAlexis** [comment]
I don't think so, I just installed it with the default. I have `hover + touch` showing under that.

**Comment by olmokramer** [comment]
I just pushed an update that ignores click events that open the context menu etc. Didn't publish it yet because I'm not entirely sure it will fix this issue. Could you please close all Atom instances and run in your terminal
1. `cd ~/.atom/packages`
2. `rm -rf autohide-tree-view`
3. `git clone https://github.com/olmokramer/atom-autohide-tree-view autohide-tree-view`
4. `cd autohide-tree-view`
5. `apm install`

and try again?

**Comment by OmgImAlexis** [comment]
That didn't seem to do anything at all. I can still use the <kbd>a</kbd> key and rightcliking still doesn't work.

**Comment by olmokramer** [comment]
Oops... I'm sorry, but I found that the mouse button checks were wrong, making it ignore _all_ mouse events... I pushed some new commits, can you pull and test again?

**Comment by OmgImAlexis** [comment]
Sure.

**Comment by OmgImAlexis** [comment]
@olmokramer doesn't seem to fix anything. :(

**Comment by olmokramer** [comment]
:cry: What packages are you using?

**Comment by OmgImAlexis** [comment]
autohide-tree-view 
merge-conflicts
seti-ui
wakatime
atom-jade
language-mako
seti-syntax
tree-view-git-status

**Comment by OmgImAlexis** [comment]
Also I'm on a Macbook pro with Yosemite.

**Comment by olmokramer** [comment]
Hi, I'm sorry I went quiet all of a sudden. I'm on vacation right now and this kinda slipped through with the preparations etc... I'll take another look when I'm back, though I still haven't been able to reproduce this.

**Comment by austinfox** [comment]
I just installed autohide-tree-view and am also experiencing this issue. When I try to rename a file from the tree view, the modal to rename the file flashes for a few milliseconds and then disappears. I have a mac with Yosemite, and I have confirmed that renaming a file after  disabling this plugin works as intended.

**Comment by olmokramer** [comment]
Can you add the following snippet on line 144 in `~/.atom/packages/autohide-tree-view/lib/commands.js`

``` js
for(let command of [
  'command-palette:toggle',
  'tree-view:add-file',
  'tree-view:add-folder',
  'tree-view:duplicate',
  'tree-view:rename',
]) {
  atom.commands.add('atom-workspace', command, clearFocusedElement);
}
```

Then restart Atom and try again. If this doesn't work, I don't know what will... :confused:

**Comment by OmgImAlexis** [comment]
Tried it and it doesn't seem to change anything. :cry:

**Comment by olmokramer** [comment]
Too bad :( I'll keep thinking about a possible solution. For adding files, I recommend using [advanced-new-file](https://atom.io/packages/advanced-new-file) in the meantime, it's really good!

**Comment by OmgImAlexis** [comment]
What if you forced the sidebar to be pinned between right clicking and the new file dialog appearing, when it closes change it back to autohide?

**Comment by olmokramer** [comment]
Pinning when a modal panel is opened is a bit too aggressive IMO. I'll look into that, but I'll put it behind a setting. Thinking about it, I don't know if it's gonna work, right-clicks in the browser can be a bitch...

**Comment by rugk** [comment]
> Pinning when a modal panel is opened is a bit too aggressive IMO.

Why? If you e.g. delete a file with the context menu it's the same thing.
Although I think that the tree view stays 'pinned' is more a technical reason, but it shows how it can be done with rename and so on too.

**Comment by olmokramer** [comment]
Yeah, I've come back from that opinion. I see it makes more sense than I thought it would. I'll see what I can do. The problem seems to be, though, that it won't detect when a modal panel has opened... @OmgImAlexis (and/or others) can you run the following in the DevTools console, and then open a few modal panels (i.e. try creating a new file a few times from the tree view). What is the output in the console?

``` js
atom.workspace.panelContainers.modal.onDidAddPanel(function() {
  console.log(arguments);
});
```

**Comment by lukescott** [comment]
I think I'm having the same problem. When the tree view is un-pinned the rename dialog just flashes (disappears quickly). If I pin the tree view it doesn't disappear on me. I ran that code in dev tools and the output appears to be the same in both cases:

<img width="486" alt="screen shot 2015-09-14 at 12 37 24 am" src="https://cloud.githubusercontent.com/assets/486224/9844560/07bd5602-5a79-11e5-8d20-dd3c6fb8e020.png">

**Comment by OmgImAlexis** [comment]
I'm getting the same as @lukescott.

**Comment by olmokramer** [comment]
That looks like it should, so the problem's not there... Anyway, I've done some updates and I think it may have solved your problems as well. Could you check out the latest master and verify if this works or not?

```
cd ~/.atom/packages
rm -rf autohide-tree-view
git clone https://github.com/olmokramer/atom-autohide-tree-view autohide-tree-view
cd autohide-tree-view
apm install
```

**Comment by lukescott** [comment]
@olmokramer still doesn't work. The difference is now the tree view hides itself when I try to rename whereas before the tree view would not hide as long as my mouse remained over it. Pinning also no longer works.

It seems very random. Something is causing the rename dialog to hide itself. A couple things I noticed:

1) With the plugin disabled if you click anywhere outside the rename dialog it causes it to disappear. Could the tree view be causing an event?
2) Sometimes it works. Most of the time it doesn't. Sometimes you can see the dialog disappear, and other times you can't see it at all. Seems like a timing issue / race condition.

Not sure if it matters, but I'm using a Mac.

**Comment by olmokramer** [comment]
1. Yes, the tree view triggers a focus event on the element that had focus before the tree view opened. Whenever a modal panel opens (like the tree view dialogs, the command panel etc.), though, it should clear the element that focus should be restored to.
2. That's what I thought, so I've delayed the restoring of focus until after the animation... but apparently to no avail :cry:

> Not sure if it matters, but I'm using a Mac.

That's the weird thing... It shouldn't matter, but this seems to only happen on Mac...

BTW, what settings are you using for autohide-tree-view?

**Comment by lukescott** [comment]
> Yes, the tree view triggers a focus event on the element that had focus before the tree view opened. Whenever a modal panel opens (like the tree view dialogs, the command panel etc.), though, it should clear the element that focus should be restored to.

That's what's causing it. I did some testing with the stock tree-view (atom-autohide-tree-view disabled): 
- 1) placed carret in file on a line 2) right click on menu item -- File still has focus
- 1) placed carret in file on line 2) clicked on tree-view -- File no longer has focus and doesn't get it back unless I click on the fie again

With atom-autohide-tree-view enabled hovering over the tree-view causes the file to lose focus. Hovering out of the tree view causes the file to regain focus. Clicking on the tree-view after hovering over it and then hovering out still makes the file regain focus.

From observation this seems to be what is happening:

1) tree-view is given focus
2) file loses focus
3) dialog gains focus
4) tree-view loses focus
5) tree-view hides because it loses focus
6) because tree-view loses focus it restores focus to file
7) focus is restored to file
8) dialog loses focus and disappears
9) depending on timing the tree-view gains focus again due to the mouse "re-entering" the area (even though it didn't leave) canceling the hide animation from step 5.

This seems to only happen on hover, which is the default setting. That's what I have (the defaults).

Does the tree-view need to be given focus on hover? If the tree-view only gained focus by the user clicking on it, as it does with the stock tree-view, you wouldn't need to restore focus, and in turn that would not cause the dialog to lose focus and close.

I wonder if right-clicking on Mac causes a right-click event or if there is a difference is focus. From what I can tell right-clicking does not cause a focus change.

**Comment by olmokramer** [comment]
> 6) because tree-view loses focus it restores focus to file

Yes, but that _should_ be cancelled by [this line](https://github.com/olmokramer/atom-autohide-tree-view/blob/master/lib/commands.js#L141) where the element that would have been focused after closing the tree view is cleared when a modal panel opens, so that there is no element to restore focus to. I tried to set it to restore focus to the panel, but every panel uses different rules for when to hide. For example, the tree view dialogs hide when the text input field loses focus, while others close when the container element in the dialog loses focus. I can't account for all those differences.

> Does the tree-view need to be given focus on hover? If the tree-view only gained focus by the user clicking on it, as it does with the stock tree-view, you wouldn't need to restore focus, and in turn that would not cause the dialog to lose focus and close.

It allows for keybindings to be used right after opening the tree view. I find this a very useful feature and I won't remove it, but I can add a setting to enable/disable it. Wish I had thought of that before... I'll add the setting and push a new version in a few minutes.

**Comment by olmokramer** [comment]
Ok, pushed some new commits. If you disable the `autoHoverTreeView` setting, it should skip the focusing checks. Can you test again?

**Comment by lukescott** [comment]
> Yes, but that should be cancelled by this line where the element that would have been focused after closing the tree view is cleared when a modal panel opens, so that there is no element to restore focus to. 

I'm not sure it does. Perhaps this is happening before it is cleared.

> It allows for keybindings to be used right after opening the tree view. I find this a very useful feature and I won't remove it

Which key-bindings specifically? Do those key-bindings still work on the stock tree-view even though you haven't clicked on it?

If the key-bindings don't work without giving the tree-view focus, could you capture the key events on a higher level and pass them through to the tree-view when it is open?

> I can add a setting to enable/disable it. Wish I had thought of that before... I'll add the setting and push a new version in a few minutes.
> Ok, pushed some new commits. If you disable the autoHoverTreeView setting, it should skip the focusing checks. Can you test again?

That fixed it!

**Comment by olmokramer** [comment]
> Which key-bindings specifically? Do those key-bindings still work on the stock tree-view even though you haven't clicked on it?

Things like the arrow keys for navigation, <kbd>a</kbd> for add file, <kbd>m</kbd> to move/rename a file etc. The keys only work when the tree view is focused, so that's why I put the focusing stuff in in the first place. I removed it once by accident, and I immediately got a complaint :p

> If the key-bindings don't work without giving the tree-view focus, could we capture the key events on a higher level and pass them through to the tree-view when it is open?

All that is implemented in the actual tree-view package, so it would be a real hassle with a very high chance of breakage. So I'd rather not.

> That fixed it!

Yay! :D There's still some other things I'd like to address (all of a sudden it's become impossible to click the pin icon, for example) before publishing this, but it'll be up in a few days. Thanks for your input (and patience)! I really appreciate it.

Damn, UI/UX is tough!

PS:

> If you disable the `autoHoverTreeView` setting

I meant `autoFocusTreeView` of course...

**Comment by lukescott** [comment]
> All that is implemented in the actual tree-view package, so it would be a real hassle with a very high chance of breakage. So I'd rather not.

I have a solution. Listen to the keydown event on the capture phase. If the mouse is inside the tree-view give it focus. This will allow the key bindings to work.

Here is an example:

http://jsfiddle.net/45du0bxz/

Click outside the text-field so that the frame has focus. Start typing. Notice how the letter you pressed is now inside the text field. Click outside the text-field again, then start typing again.

When the tree-view gains focus you can keep it open all the time - moving the mouse out does not dismiss it. It only hides when it loses focus. You could restore focus if the user presses the Escape key (only if the tree-view has focus).

**Comment by olmokramer** [comment]
An interesting technique, but it would require the mouse to be in the tree view. I can also open the tree view with keybindings (<kbd>ctrl-\</kbd> by default), and I'd still want keybindings to work. And what if a user rebound the <kbd>a</kbd> to a complex key combo (e.g. <kbd>ctrl-a ctrl-z</kbd>)? I'll gladly let Atom handle that, and respond to the commands that are triggered by the keybindings, otherwise I would basically rewrite Atom's keybindings module... I'll have to respond to the commands anyway, because they can also be triggered from the command palette, or even from javascript (maybe even in third party packages).

**Comment by lukescott** [comment]
If the tree-view has been opened by a hover, the mouse is already in the tree-view. Once focus is given to the tree-view via the capture event it keeps it. And it would stay open with focus even if the mouse moved out of it. All key events would go to the tree-view at that point. Focus can only be restored by pressing <kbd>ctrl-\</kbd> while the tree view has focus. 

The <kbd>ctrl-\</kbd> binding would toggle the tree-view's get focus/restore focus just as it does now. 

The main difference is the tree-view would never try to restore focus when it loses it due to something else grabbing focus. It only does so when the user chooses to through <kbd>ctrl-\</kbd>.

Here are the use-cases I can think of:
- If the user hovers over the tree view it isn't given focus, so moving the mouse out would not change what currently has focus.
- If the user hovers over the tree view and presses a key, the tree view has focus. The tree-view would remain open until it no longer has focus, even when the mouse moves out. The user would click somewhere else to give something else focus and take it away form the tree-view.
- If the user hovers over the tree view and presses a key, the tree view has focus. They can press <kbd>ctrl-\</kbd> to close the tree-view and restore focus to the previous thing.
- If the user presses <kbd>ctrl-\</kbd> the tree view gets focus. If they press <kbd>ctrl-\</kbd> again it will close the tree-view and restore focus to the previous thing.
- If the user clicks on the edge of the tree-view it is given focus. The tree-view remains open until they click somewhere else. If they press <kbd>ctrl-\</kbd> it restores focus to the previous thing.
- If the user touches the edge of the tree-view it is given focus. It remains open until they touch something else outside of it.

**Comment by olmokramer** [comment]
Ok, I've changed a few things. I'll go through your points to discuss the changes.

> - If the user hovers over the tree view it isn't given focus, so moving the mouse out would not change what currently has focus.

I've kept the auto focus setting to control this, although I've changed it so it will only apply to hover events. Also I've renamed it to `autoFocusTreeViewOnHover`.

> - If the user hovers over the tree view and presses a key, the tree view has focus. The tree-view would remain open until it no longer has focus, even when the mouse moves out. The user would click somewhere else to give something else focus and take it away form the tree-view.

Wouldn't this still be problematic? If the tree view gets focus when pressing the <kbd>a</kbd> key, won't you still get the disappearing dialogs, because the tree view tries to unfocus (i.e. focus something else)? I'd still rather leave the keyboard event handling to Atom core. I would also find it unacceptable if the tree didn't hide on a mouseout.

> - If the user hovers over the tree view and presses a key, the tree view has focus. They can press <kbd>ctrl-</kbd> to close the tree-view and restore focus to the previous thing.
> - If the user presses ctrl-\ the tree view gets focus. If they press ctrl-\ again it will close the tree-view and restore focus to the previous thing.
> - If the user clicks on the edge of the tree-view it is given focus. The tree-view remains open until they click somewhere else. If they press ctrl-\ it restores focus to the previous thing.
> - If the user touches the edge of the tree-view it is given focus. It remains open until they touch something else outside of it.

Because the auto focus setting now only applies to hover events, these should work as you describe.

Please pull the master branch and let me know what you think.

**Comment by lukescott** [comment]
> Wouldn't this still be problematic? If the tree view gets focus when pressing the a key, won't you still get the disappearing dialogs, because the tree view tries to unfocus (i.e. focus something else)? I'd still rather leave the keyboard event handling to Atom core. I would also find it unacceptable if the tree didn't hide on a mouseout.

Yes it probably would. Then perhaps hover should not take focus at all unless you click.

I tried keeping the focus (turned off that setting) and started using "none" and toggled the tree-view with key-bindings. I ran into an issue where I was trying to do a find on a directory and focus ended up in the editor instead of the find dialog.

> Because the auto focus setting now only applies to hover events, these should work as you describe. Please pull the master branch and let me know what you think.

Perhaps this will help out with the issue I just described. Will do, thanks!

**Comment by lukescott** [comment]
Ok, a couple things I've noticed:
- With hover mode and the focus option turned on the rename issue still happens. With it turned off it works. Awesome!
- The above issue I mentioned is fixed - If I open the dialog with <kbd>Ctrl-\</kbd>, right click and choose `Search in Directory` the focus goes to the search box and the tree-view stays open. So far so good. However, if I press <kbd>Ctrl-\</kbd> again to dismiss while in the search box, the focus is restored to my editor. -- I would keep it exactly like it is with the tree-view remaining open until <kbd>Ctrl-\</kbd> is pressed, but I would only restore the focus if the tree-view has it.

As far as hover mode is concerned, perhaps you could only restore focus on mouse out if the tree-view currently has the focus. That way if the dialog pulls it away a mouse out will not cause a focus restore.

I'll let you know if I notice anything else. I'm somewhat torn between hover and pure keyboard activation. After a couple days using just <kbd>Ctrl-\</kbd> I'm still trying to open it with hover though.

**Comment by olmokramer** [comment]
> As far as hover mode is concerned, perhaps you could only restore focus on mouse out if the tree-view currently has the focus. That way if the dialog pulls it away a mouse out will not cause a focus restore.

Good one! I also just thought of that. I'll see what I can do :)

**Comment by olmokramer** [comment]
Ok, just built it and it seems to work fine! I have also removed the part that clears the previously focused element when a new modal dialog opens, because with this fix it shouldn't be necessary. Please let me know if everything's still fine on your end.

> I'm somewhat torn between hover and pure keyboard activation.

Then why not use both :)

**Comment by lukescott** [comment]
Not working on my end. I wonder if the context menu causes a mouse out event. As soon as I click on the context menu action the tree-view collapses and I haven't moved the mouse away from it.

Do you have a Mac to test with?

**Comment by lukescott** [comment]
I did a bit of debugging. I'm not sure if it's the context menu, but a mouse leave event does get triggered after choosing an item from the context menu. And a mouse enter is probably caused after. That would cause the focus issue with the rename dialog.

**Comment by olmokramer** [comment]
I added some more logic around the tree view focusing. If anything inside a modal panel is focused, it will refuse to focus the tree view. It's working really well for me now! I can't replicate the issues with the right mouse clicks, though. I'll check if I can do anything about that.

> Do you have a Mac to test with?

Nope :( and it probably won't happen in the near future...

**Comment by lukescott** [comment]
I'll give it a try, thanks!

I think you can install OS X as a virtual machine. I've seen some stuff about doing it on VMWare.

**Comment by lukescott** [comment]
It works! There is just one issue - If I use hover and choose "Search in Directory" that doesn't work. Using <kbd>Ctrl-\</kbd> instead of hover works though.

The "Search in Directory" doesn't disappear, it just loses the focus immediately. Not sure what to do there :).

Perhaps we can do a screen share and you can test on my machine.

**Comment by olmokramer** [comment]
Awesome! :D Just to be sure, does it work even with the `autoFocusTreeView` setting enabled?

**Comment by lukescott** [comment]
Yep, just have same issue with search though.

**Comment by olmokramer** [comment]
Ok, then I'll remove the setting again. Right now, I check if `document.activeElement` is a child of a `atom-panel.modal`, and cancel the focusing of the tree view if that's true. I could also do this for find-and-replace, etc. but it would mean that I would have to explicitly keep a list of elements/selectors that cancel tree view focusing. That's OK for core packages, but I don't really want to keep track of every single package out there that adds a panel that should keep focus or not...

autohide-tree-view does already provide a service so other packages can show/hide/pin/unpin the tree view. I could add a function to the service that disables the tree view focusing on specific elements, so packages can control it themselves.

Thanks for the offer regarding the screen sharing session, but I think I understand why it is happening. Now it's more about picking the least painful solution to support every scenario.

**Comment by lukescott** [comment]
The main thing is if the tree-view blurs it shouldn't be restoring focus. The problem is that mouse even is causing in/out to make the tree-view refocus itself. This seems to be related to the context menu. There is a context menu event, so maybe we could use that somehow?

Another thought I had is can you determine what element the mouse is over when the mouse out occurs. I wonder if in the case of the context menu if the element is null/undefined. Perhaps you could ignore the mouse out in this case.

**Comment by olmokramer** [comment]
As I said in #43, I wanted to wait with the release of the new version until this was resolved. I feel we're really close to a solution here, but there's a lot of other fixes in this version that I just want to get out. I'm just going to release it tomorrow as it is right now. We can continue our efforts to resolve these focusing issues after that. I've pushed some new commits to the master branch, could you try one last time if it still works? Then I think I'm ready to publish the new version :smile:.

> The main thing is if the tree-view blurs it shouldn't be restoring focus. The problem is that mouse even is causing in/out to make the tree-view refocus itself. This seems to be related to the context menu. There is a context menu event, so maybe we could use that somehow?

How about we ignore the next `mouseenter` event in the `contextmenu` event, and then re-enable it again the next time the tree view hides. I'm not entirely sure this will work all the time, I'll think about it.

> Another thought I had is can you determine what element the mouse is over when the mouse out occurs. I wonder if in the case of the context menu if the element is null/undefined. Perhaps you could ignore the mouse out in this case.

I think this is more complicated than the solution I proposed above. I'd rather try that first.

**Comment by lukescott** [comment]
> could you try one last time if it still works? Then I think I'm ready to publish the new version

Sure I'll give it a try.

> How about we ignore the next mouseenter event in the contextmenu event, and then re-enable it again the next time the tree view hides. I'm not entirely sure this will work all the time, I'll think about it.

I think the mouse event happens after choosing an item in the context menu. Will definitely require some further testing.

**Comment by lukescott** [comment]
Ok so it works as it did in the last commit - so rename works. Although when I use <kbd>Ctrl-\</kbd> and try to search it also loses focus just like hover - unless I switch show on to something other than "hover", such as "none". So I still have a work-around for that at least.

**Comment by olmokramer** [comment]
Ok, great! I'll publish the new version in a few minutes, then we can work on the other focusing issues next week. I'm going to close this issue and open a new one to continue discussion, as the renaming dialog issue is resolved now! :D Thanks again for your input!
