### ISSUE TITLE
Can't turn off the Push Editor option

### ISSUE THREAD

**Issue by feimosi** [olmokramer/atom-autohide-tree-view#32]
Every time I run the Atom editor this option is turned on by default (although the checkbox is not ticked). If you change it back, it stays with the current sessions till I close the editor. 
I want to turn it off because it really lags, even on a descent i5 machine.

My packages:

atom-beautify@0.28.8
auto-detect-indentation@0.4.2
autocomplete-sass@0.1.0
autohide-tree-view@0.22.0
color-picker@2.0.11
emmet@2.3.12
file-icons@1.5.8
highlight-selected@0.10.1
linter@1.2.4
linter-jshint@1.1.4
merge-conflicts@1.3.4
minimap@4.12.0
minimap-highlight-selected@4.3.0
pigments@0.9.0
sync-settings@0.5.0

**Comment by olmokramer** [comment]
Hi, thanks for the report. This looks like your config isn't saved to file. If you change other settings, do they persist upon restart of Atom? Is your `~/.atom/config.cson` writable?

Could you try editing your `config.cson` by hand, and see if it works that way? Add `'pushEditor': false` to the `'autohide-tree-view'` section of your config

**Comment by feimosi** [comment]
Ok, so after a few tests the thing looks like this: `config.cson` is writable. When I change other settings they get appended to the config. If I check Push Editor option, the property `pushEditor: true` is added, but when I uncheck it, then it gets removed. Also when I place it myself with `false`, after a restart it disappears. All other settings seem to be preserved.

**Comment by olmokramer** [comment]
Hmmm... That's very weird. I'll look at it tonight.

**Comment by olmokramer** [comment]
I found there were indeed some issues with the `pushEditor` setting. I've fixed that, but it still is so very weird that changing it didn't persist between Atom restarts. I'll publish the new version later today, please let me know if it works or not.

**Comment by olmokramer** [comment]
The new version is up. Please let me know if it fixes your issues

**Comment by feimosi** [comment]
Thanks for the update, but unfortunately it didn't help. The issue still appears, even after several restarts and trails. Also, I forgot to mention that it happens on two of my machines, each with slightly different packages installed (running Win 7 and 8.1)

**Comment by olmokramer** [comment]
Too bad... Do either of these work:
- Call `autohide tree view: toggle push editor` from the command palette
- Open the devtools console (<kbd>ctrl+shift+i</kbd> then click the console tab) and run `atom.config.set('autohide-tree-view.pushEditor', true)` (or `false`)
- Close all instances of Atom. Delete (or rename) `~/.atom/storage` and `~/.atom/config.cson` and then try again

**Comment by feimosi** [comment]
Sorry to say that, but no success...
- There isn't any `Autohide Tree View: toggle push editor` option, only `Autohide Tree View: toggle enabled`
- Setting in console works but only if I first set it to `true` and then to `false`, strange indeed. Resets after restart of course
- I've removed both, but nothing changed

It's weird you cannot reproduce this issue.

**Comment by olmokramer** [comment]
Ok, that's weird. There should be a `autohide-tree-view:toggle-push-editor` command. How about if you uninstall the package, and then the last step from the list again?

**Comment by feimosi** [comment]
I've reinstalled the package with files from the last step removed and still nothing. That's kind of a really strange thing. Next week I'll try to reinstall Atom.

**Comment by olmokramer** [comment]
Ok, this is really starting to look like something in Atom core. Packages do nothing themselves to actually save the config values to `config.cson`... Atom handles that by itself. Really weird though that it's only this one setting. How did you install Atom by the way?

**Comment by D-side** [comment]
I don't think it's related to installation method.

Same issue. Atom installed via Webupd8 PPA, Linux Mint 17.1 (based on Ubuntu 14.04).

And after a while of bug tracking-down...

**I've come up with a workaround**! Set **"show on"** to _"hover"_ in configuration.

Apparently, it errors out inside `enable` function in `touch-events.js` thus resulting in the wrong state of the view. Disabling touch events altogether seems to restore normal behavior.

**Comment by D-side** [comment]
Crashes on [this line](https://github.com/olmokramer/atom-autohide-tree-view/blob/master/lib/touch-events.js#L42):

```
disposables.add(onDidTouchSwipeLeft(swipeChange, swipeEndLeft));
```

**Comment by D-side** [comment]
Standard boatload of information from Atom's issue reporter (the instant I change back to `hover+touch`):

**Atom Version**: 1.0.7
**System**: Linux Mint
**Thrown From**: [autohide-tree-view](https://github.com/olmokramer/atom-autohide-tree-view) package, v0.24.0

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /home/d-side/.atom/packages/autohide-tree-view/lib/touch-events.js:46

TypeError: undefined is not a function
  at enable (/home/d-side/.atom/packages/autohide-tree-view/lib/touch-events.js:46:19)
  at /home/d-side/.atom/packages/autohide-tree-view/lib/commands.js:48:55
  at /opt/atom/resources/app.asar/src/config.js:557:16
  at /opt/atom/resources/app.asar/src/config.js:574:20
  at Emitter.module.exports.Emitter.emit (/opt/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Config.module.exports.Config.emitChangeEvent (/opt/atom/resources/app.asar/src/config.js:736:29)
  at Config.module.exports.Config.setRawValue (/opt/atom/resources/app.asar/src/config.js:551:19)
  at Config.module.exports.Config.set (/opt/atom/resources/app.asar/src/config.js:233:14)
  at SettingsPanel.module.exports.SettingsPanel.set (/opt/atom/resources/app.asar/node_modules/settings-view/lib/settings-panel.js:190:28)
  at HTMLSelectElement.<anonymous> (/opt/atom/resources/app.asar/node_modules/settings-view/lib/settings-panel.js:204:26)
  at HTMLSelectElement.jQuery.event.dispatch (/opt/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at HTMLSelectElement.elemData.handle (/opt/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

```

### Commands

```
  2x -1:00.5.0 tree-view:toggle (atom-text-editor.editor.is-focused)
     -0:11.8.0 settings-view:open (atom-text-editor.editor.is-focused)
```

### Config

``` json
{
  "core": {
    "autoHideMenuBar": true,
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ],
    "disabledPackages": [
      "pigments"
    ]
  },
  "autohide-tree-view": {}
}
```

### Installed Packages

``` coffee
# User
atom-material-syntax, v0.2.3
atom-material-ui, v0.5.21
autocomplete-clang, v0.8.7
autohide-tree-view, v0.24.0
browser-plus, v0.0.34
color-picker, v2.0.11
file-icons, v1.6.6
linter, v1.4.3
minimap, v4.13.0
minimap-bookmarks, v0.1.0
minimap-codeglance, v0.4.0
minimap-find-and-replace, v4.3.0
minimap-git-diff, v4.1.8
minimap-linter, v1.0.0
minimap-selection, v4.3.0

# Dev
No dev packages
```

**Comment by olmokramer** [comment]
@D-side Thanks for sharing your solution! I'll look into this and fix the issue in `touch-events.js`.

I've seen some really weird bugs happen with the versions provided by the webupd8 team that were fixed by installing the "official" build on https://atom.io. Stuff like no click events triggering on the tabs' close buttons, and only there... Can you please confirm the issue is also present in the .deb on https://atom.io?

**Comment by olmokramer** [comment]
@D-side the error in `touch-events.js` was because I forgot to check if [atom-touch-events](https://atom.io/packages/atom-touch-events) was installed/enabled when touch events were enabled. It assumed some methods provided by that package were there while in fact they weren't... I'll publish the fixed version soon.

**Comment by olmokramer** [comment]
Ok, the new version is up, please let me know if it works.

**Comment by feimosi** [comment]
I can finally confirm that the issue has been fixed. Thanks a lot!

**Comment by olmokramer** [comment]
Alright! Glad to hear that!
