### ISSUE TITLE
Autohide tree view isn't working after 012.0 update

### ISSUE THREAD

**Issue by LaurentTreguier** [olmokramer/atom-autohide-tree-view#6]
Since update 0.12.0 I haven't been able to get this plugin working. It was fine on 0.11.4, but now it has no effect, and even the commands to control it don't appear in the command list... Is there something I have missed, like something specific to do after an update ? I don't really know how plugins in Atom are made, so right now I haven't tried anything except trying to restart the plugin and the editor, without success. I see the status bar shows no error or warning about it. It feels like the entire package is ignored for some reason. What could be the problem ?

**Comment by olmokramer** [comment]
For me this only happens right after installing the package, but when I restart Atom the package seems to work. So could you try restarting Atom, and if that doesn't work uninstall the package, reinstall the package and restart Atom?

**Comment by LaurentTreguier** [comment]
I tried to reinstall, restart Atom, disable and enable, but still no luck... I tested and have the same problem on both the Linux and Windows versions of Atom (I don't know if this is of any help, but at least it doesn't seem to be some OS difference).

**Comment by olmokramer** [comment]
Hmmm.... I can't replicate this... But maybe I know what's causing the problem.

"I tested and have the same problem on both the Linux and Windows versions of Atom"
That's a good thing because it means Atom is consistent across platforms :p

**Comment by olmokramer** [comment]
I just released `v0.12.1` which <em>may</em> fix the problem. Does it work for you?

**Comment by mark-hahn** [comment]
Still doesn't work for me - hasn't for several versions -- too busy to bitch (grin)

It blocks `ctrl-\` and that's all it does.

**Comment by LaurentTreguier** [comment]
Nope, still no sign of life after updating, restarting Atom, uninstalling and reinstalling...

**Comment by mark-hahn** [comment]
windows 8.1 
atom 0.177.0
0.12.1

**Comment by LaurentTreguier** [comment]
Windows 8.1, Atom 0.178.0, plugin 0.12.1
Archlinux, Atom 0.179.0, plugin 0.12.1

**Comment by olmokramer** [comment]
I made a mistake in 0.12.1. I uploaded 0.12.2, could you try that one?

**Comment by olmokramer** [comment]
If it still doesn't work, could you try from the command palette `Tree View: Show` and then restart Atom?

**Comment by mark-hahn** [comment]
0.12.3 fixed it.

But just to prove you can never make everyone happy, I'd like to point out
that the initial width of one pixel was too narrow for me to open it.  I
thought it was broken until I went to the settings.

**Comment by olmokramer** [comment]
That's great! I'm working on a new version (again) that should be more reliable than the current one

That's a good point about the width. I'll set the default to 5px

**Comment by olmokramer** [comment]
Thanks for the feedback! :)

**Comment by olmokramer** [comment]
I just uploaded the new version, 0.13.0. Does it work for you as well after either updating or installing?

**Comment by LaurentTreguier** [comment]
It works again ! I just had to disable and re enable it. Thanks !

**Comment by LaurentTreguier** [comment]
Actually I might have been too hasty closing this... It works when disabling and re enabling, but it has to be done every time Atom is restarted. Still, when it's done it works like a charm.

**Comment by olmokramer** [comment]
I'll look into it

**Comment by olmokramer** [comment]
I can't seem to replicate the need to disable/enable after Atom restart. Could you try removing your `~/.atom/storage` directory (or renaming it to `storage.bak` if you want a backup)?

If that doesn't work, you could add this to your `~/.atom/init.coffee` as a workaround until I found a solution:

``` coffee
atom.packages.onDidActivateInitialPackages ->
  atom.commands.dispatch 'atom-workspace', 'autohide-tree-view:disable'
  atom.commands.dispatch 'atom-workspace', 'autohide-tree-view:enable'
```

**Comment by LaurentTreguier** [comment]
Removing ~/.atom/storage didn't work... I found no file named "init.coffee" in ~/.atom, and creating it didn't change anything. I tried to disable every other plugin, still without success. It seems weird that you can't replicate this behavior, maybe it's caused by something I did ? I think I'll try some things.

**Comment by LaurentTreguier** [comment]
Hey ! Just went on Windows and opened a file using right click and "Open with Atom". If I open files this way, the plugin works just fine.

**Comment by olmokramer** [comment]
At least that's something :) I'm still looking into it, but I can't find a reason why it shouldn't work... I created a new branch `bug-6`. Would you be so kind and run the following commands inside the `~/.atom/packages` directory to clone that repo (so I can push without having to release a new version every time) (these instructions are for Linux, so you'll have to translate them to Windows):
- `cd ~/.atom/packages`
- `rm -rf autohide-tree-view`
- `git clone -b bug-6 https://github.com/olmokramer/atom-autohide-tree-view`

And each time I push something you'll have to run `git pull` from the `~/.atom/packages/autohide-tree-view` directory.

First, can you tell me if you see `autohide-tree-view: activating` and `autohide-tree-view: done activating` after cloning the package? And if it logs either `autohide-tree-view: initialize after activate initial packages` or `autohide-tree-view: initialize before activate initial packages` or nothing at all? (after cloning the `bug-6` branch)

**Comment by LaurentTreguier** [comment]
I see nothing after cloning... Where are the logs supposed to appear ?

**Comment by olmokramer** [comment]
I'm sorry, they get logged to the console inside Atom. You can open it with <kbd>ctrl-shift-i</kbd> and then click on console

**Comment by LaurentTreguier** [comment]
Just saw this in the console : `Failed to load package named 'atom-autohide-tree-view' Error: Cannot find module 'sub-atom'`

**Comment by olmokramer** [comment]
Oh right... Run `apm install` from the `~/.atom/packages/autohide-tree-view` directory to install the `sub-atom` module

**Comment by mark-hahn** [comment]
When you load a add a package by git clone or any other way that only loads
source, you have to do `apm install` in the package dir to load the modules.

**Comment by LaurentTreguier** [comment]
Oh ok. Now I see autohide-tree-view is activating :
`autohide-tree-view: activating`
`autohide-tree-view: done activating`
`Window load time: 727ms`
`autohide-tree-view: initialize after activate initial packages`

**Comment by olmokramer** [comment]
Alright, that's good. I pushed a new version, does it log `autohide-tree-view: enabling` and `autohide-tree-view: enabled`?

**Comment by LaurentTreguier** [comment]
Nope, it now logs `autohide-tree-view: enable` in addition to the rest.

**Comment by olmokramer** [comment]
Ok so that means something is going wrong while enabling the package. It's logging a lot more lines now in addition to the actual error (if there is one, but there should be). Could you tell me the last of the following lines that gets logged, and the error that gets logged?
1. 'autohide-tree-view: enable'
2. 'autohide-tree-view: tree-view package active: '
3. 'autohide-tree-view: tree-view package found: '
4. 'autohide-tree-view: tree-view model: '
5. 'autohide-tree-view: tree-view element: '
6. 'autohide-tree-view: applied setting hiddenWidth'
7. 'autohide-tree-view: applied setting animate'
8. 'autohide-tree-view: enabled'

**Comment by LaurentTreguier** [comment]
It goes on correctly until `autohide-tree-view: tree-view element:` and right after that : `TypeError: Cannot set property 'width' of undefinedmessage: "Cannot set property 'width' of undefined"stack: (...)get stack: function () { [native code] }set stack: function () { [native code] }__proto__: Error`

**Comment by olmokramer** [comment]
We're getting closer! Thanks for taking the time to go through this with me! You mentioned earlier you had problems on both Windows and Linux, are your problems still on both of them?

I just pushed again, it should now log three booleans after the `autohide-tree-view: tree-view-element:`, can you tell me those?

**Comment by LaurentTreguier** [comment]
For now I am only testing on Linux (it's easier to use git and apm I think). The three booleans are : `autohide-tree-view:  true true false`

**Comment by olmokramer** [comment]
Hmmm... that's a little weird, it's saying that the `parentNode` of the tree-view's element doesn't have a `style` property. It should now log that parentNode, is it an HTML element that gets logged? Something like `<atom-panel class="...">...</atom-panel>`

**Comment by LaurentTreguier** [comment]
`autohide-tree-view: #document-fragment`
If I expand the `#document-fragment` it shows : `<div class="tree-view-resizer tool-panel autohide autohide-hover-events" data-show-on-right-side="false" is="space-pen-div" style="width: 1px;"><div class="tree-view-scroller"><ol class="tree-view full-menu list-tree has-collapsable-children focusable-panel" tabindex="-1"></ol></div><div class="tree-view-resize-handle"></div></div>`

**Comment by olmokramer** [comment]
Hey! That I can reproduce, but only when I start Atom from `/usr/share/applications/atom.desktop`, which I had never done. Thanks again for helping out! I'll try to figure out what is causing the document-fragment thing

**Comment by LaurentTreguier** [comment]
Hey, you are right ! When I start Atom from the console, everything works fine. I just usually start it from a dock on my graphical interface, which surely is linked to `/usr/share/applications/atom.desktop`.

**Comment by olmokramer** [comment]
So what is exactly not working for you? When I open Atom with the `.desktop` shortcut there is no tree view (as expected), then when I open a file, the tree view appears minimized (as expected) and when I hover the tree view expands (as expected) but the animation does not work (not as expected)

**Comment by LaurentTreguier** [comment]
I am running gnome 3.14 as desktop environment. When I installed Atom, it automatically appeared in my graphical list of apps. When launching it, the plugin doesn't work. When launching from the console with `/usr/share/atom/atom`  it doesn't work either. However when I launch with the command `atom` (which is linked to `/usr/bin/atom`), the plugin works, but without animation, exactly as you just described.

**Comment by olmokramer** [comment]
What does Atom open when you open it with either of those commands? An `untitled` file or a directory/project?

**Comment by olmokramer** [comment]
Also could you print the list of installed packages? You can get it with `apm list --installed --packages`

**Comment by olmokramer** [comment]
I pushed a new version which seems to fix the problems for me

**Comment by LaurentTreguier** [comment]
It seems to work on my end too ! Without animation, but now it works whatever I do to open Atom !

**Comment by olmokramer** [comment]
And does animation now also work? I pushed a new version

**Comment by LaurentTreguier** [comment]
No, still no animation.

**Comment by olmokramer** [comment]
And now?

**Comment by LaurentTreguier** [comment]
Still no animation. But I'm happy now that the main problem is gone :)

**Comment by olmokramer** [comment]
Glad you're happy :), but now I'm not happy cause it doesn't work :( and this one I just can't reproduce 

I pushed a last try...

**Comment by LaurentTreguier** [comment]
I'm sorry to say that it still doesn't work. I'll close this issue since the main bug is fixed and the animation is not a critical part of the package.

**Comment by olmokramer** [comment]
Ok. Thanks one last time for helping me out here!

**Comment by olmokramer** [comment]
I published a new version, 0.14.0, on apm. You can now delete the `~/.atom/packages/autohide-tree-view` directory and install with `apm install autohide-tree-view`

**Comment by LaurentTreguier** [comment]
You don't have to thank me, I thank you for listening to my problem and fixing it ! also, did you try something else about the animation ? Because in 0.14.0 it's working.

**Comment by olmokramer** [comment]
0.14.0 just merged the `bug-6` branch into master, so no changes since then... Weird... Anyway, glad to hear the animations are working :)
