### ISSUE TITLE
Can't scroll in treeview

### ISSUE THREAD

**Issue by pwr22** [olmokramer/atom-autohide-tree-view#77]
Without this addon I can scroll down in the tree view as needed. WIth this addon, scrolling no longer works

This was with the latest version, so **v0.25.1** I assume

**Comment by exdeniz** [comment]
Scroll work on "Push" only, please fix it

**Comment by chl1996** [comment]
+1

**Comment by elcarim5efil** [comment]
you might just add some code in the style file.

``` css
.tree-view-resizer {
  ...
  height: 100% !important;
  ...
}
This should fix the problem temporarily.
```

**Comment by elcarim5efil** [comment]
However, I just find out that the latest master version has just fix this problem, you might try updating the  package to the latest version on this github.

**Comment by austinkelleher** [comment]
+1 I am seeing this issue too @olmokramer

**Comment by selfagency** [comment]
+1 still, going on months now

**Comment by OmgImAlexis** [comment]
@olmokramer any updates on this? Scrolling seems to only work if you pin the tree view.

**Comment by sebastianarena** [comment]
+1 !

**Comment by DamageESP** [comment]
The issue is still going on.

@elcarim5efil's piece of code fixes it though. Thanks dude.

**Comment by buschtoens** [comment]
Just updated Atom to v1.17.0 and experienced the same issue. Then I updated all packages and restarted Atom. The issue was resolved then.

**Comment by jperezlatimes** [comment]
Experiencing this as well in v1.17.0x64. Updated all my packages and restarted like @buschtoens mentioned, but I'm still unable to scroll the treeview.

**Comment by jperezlatimes** [comment]
Update: It appears to be a bug in the theme I was using: Atom Material. Switching back to an out-of-the-box theme re-enabled treeview scrolling.

**Comment by buschtoens** [comment]
Interesting. I'm also using Material Dark.

**Comment by OkayItsMikael** [comment]
I had the same issue, using Material Dark. Updating all packages and restarting worked for me.

**Comment by ezeikel** [comment]
Issue still present. Also using Material Dark. Above css didn't work for me but this did:

`.tree-view {
  overflow: scroll;
}
`

**Comment by olmokramer** [comment]
Hi everyone, I'm sorry for the extremely late reply. As you have probably noticed I've stopped maintaining my Atom plugins a few years ago. I got very frustrated with how Atom was maintained and started ignoring all of my plugins. I'm sorry for that. I won't install Atom to test and mergeer PRs, but I'd be happy to transfer my repositories to anyone that wants to maintain any of my plugins. Again, I'm sorry.

**Comment by DamageESP** [comment]
Don't worry, at this point most devs have switched to VS Code... 😆

Thanks for your work anyways. 👍

**Comment by pwr22** [comment]
Yeah... I opened the issue here but I'm now a long ago convert to VSCode :man_shrugging:
